const employees = [
    {
        maNhanVien: 'NV01',
        tenNhanVien: 'Le Nhat Duy',
        namSinh: 1999,
        soDienThoai: '0123121632',
        gioiTinh: 'Nam',
        quyen: 'Manager',
        tenTaiKhoan: 'admin',
        matKhau: '1111',
    },
    {
        maNhanVien: 'NV02',
        tenNhanVien: 'Tran Duc Dai Phat',
        namSinh: 1999,
        soDienThoai: '0123126236',
        gioiTinh: 'Nam',
        quyen: 'Employee',
        tenTaiKhoan: 'user',
        matKhau: '1111',
    },
    {
        maNhanVien: 'NV03',
        tenNhanVien: 'Dương Thế Khánh',
        namSinh: 1999,
        soDienThoai: '0123122683',
        gioiTinh: 'Nam',
        quyen: 'Employee',
        tenTaiKhoan: 'user1',
        matKhau: '1111',
    },
    {
        maNhanVien: 'NV04',
        tenNhanVien: 'Đàm Đình Thịnh',
        namSinh: 1999,
        soDienThoai: '0123121893',
        gioiTinh: 'Nam',
        quyen: 'Employee',
        tenTaiKhoan: 'user2',
        matKhau: '1111',
    },
    {
        maNhanVien: 'NV05',
        tenNhanVien: 'Đặng Phạm Thiên Khải',
        namSinh: 1999,
        soDienThoai: '0123121993',
        gioiTinh: 'Nam',
        quyen: 'Employee',
        tenTaiKhoan: 'user3',
        matKhau: '1111',
    },
    {
        maNhanVien: 'NV06',
        tenNhanVien: 'Đào Ngọc Anh',
        namSinh: 1999,
        soDienThoai: '0123122576',
        gioiTinh: 'Nữ',
        quyen: 'Employee',
        tenTaiKhoan: 'user4',
        matKhau: '1111',
    },
    {
        maNhanVien: 'NV07',
        tenNhanVien: 'Đỗ Minh Hào',
        namSinh: 1999,
        soDienThoai: '0123121899',
        gioiTinh: 'Nam',
        quyen: 'Employee',
        tenTaiKhoan: 'user5',
        matKhau: '1111',
    },
    {
        maNhanVien: 'NV08',
        tenNhanVien: 'Đỗ Tiến Lượng',
        namSinh: 1999,
        soDienThoai: '0123127436',
        gioiTinh: 'Nam',
        quyen: 'Employee',
        tenTaiKhoan: 'user6',
        matKhau: '1111',
    },
    {
        maNhanVien: 'NV09',
        tenNhanVien: 'Hùynh Minh Thư',
        namSinh: 1999,
        soDienThoai: '0123123356',
        gioiTinh: 'Nữ',
        quyen: 'Employee',
        tenTaiKhoan: 'user7',
        matKhau: '1111',
    },
]

module.exports = employees;